### PR TITLE
feat: Add an example for uploading NFT images with metadata

### LINKED ISSUE #8: Demo program for upload images based on default folder
**Is your feature request related to a problem? Please describe.**
I just think this project needs a simple demo program.

**Describe the solution you'd like**
I'm going to make a simple demo. I plan to implement a simple default folder to upload low-pixel images. This will not affect the volume of the whole project.

### PR DESCRIPTION
**Pull request by rhcproc**
- close #8

### CODE REVIEW

**Comment by rhcproc** [comment]
Hi @837477. These days, I am searching for uploading NFT images, and this repository is very helpful. I thought that NFT uploading examples make it convenient for others. Then, I make a simple NFT uploading example and request PR.

**Review by 837477 — APPROVED** [review]
@rhcproc ! Rrrrreally appreciate your contribution. 👍 
I hope many people will benefit from this example sample.

**Comment by 837477** [comment]
@rhcproc, Have you ever followed the Python PEP 8 style guide rules? (IPyFS adheres to Python PEP 8 style conventions 😂)
If this rule has not been applied, please apply it when you have time. 🙏🏻

**Comment by rhcproc** [comment]
Hi, I just apply the rule of characters 79 In the PEP8 style guidelines.  If you want to apply another rule of PEP8, please let me know which one should apply. Thank you for approving this PR :D

**Review by 837477 — APPROVED** [review]
LGTM !!

**Pull request merged**
